import {
  belgium,
  canada,
  southKorea,
  india,
  sweden,
  uae,
  usa,
  greece,
  hongKong,
  uk,
  singapore,
  switzerland,
  nigeria,
  philippines,
  bangladesh,
  mexico,
  brazil,
  turkey,
  japan,
} from "@/public/country-flag";

export const COUNTRY_FLAGS = [
  { name: "SWITZERLAND", flag: switzerland },
  { name: "SINGAPORE", flag: singapore },
  { name: "UAE", flag: uae },
  { name: "INDIA", flag: india },
  { name: "SOUTH KOREA", flag: southKorea },
  { name: "SWEDEN", flag: sweden },
  { name: "UK", flag: uk },
  { name: "CANADA", flag: canada },
  { name: "NIGERIA", flag: nigeria },
  { name: "HONG KONG", flag: hongKong },
  { name: "GREECE", flag: greece },
  { name: "USA", flag: usa },
  { name: "BELGIUM", flag: belgium },
  { name: "PHILIPPINES", flag: philippines },
  { name: "BANGLADESH", flag: bangladesh },
  { name: "MEXICO", flag: mexico },
  { name: "BRAZIL", flag: brazil },
  { name: "TURKEY", flag: turkey },
  { name: "JAPAN", flag: japan },
];
