import {
  bitcoin,
  bitcoininsider,
  bitget,
  bittwome,
  blockchainmagazine,
  blockchainreporter,
  blockchaintoday,
  blockhead,
  catenaa,
  cim,
  coinchapter,
  coincu,
  coinedition,
  coingape,
  coinpasar,
  coinpedia,
  coinrank,
  coinwire,
  cryptobreakingnews,
  cryptodashnews,
  cryptodotnews,
  cryptonews,
  cryptopolitan,
  cryptoslate,
  cryptoweekly,
  disruptionbanking,
  dlnews,
  droomdroom,
  forklog,
  fxstreet,
  klarda,
  koreaittimes,
  newschain,
  ngglobalmedia,
  santiment,
  startupnews,
  theblockpedia,
  thecoinrepublic,
  thecryptonomist,
  thejournalwire,
} from "@/public/images/ecosystem-new/mp";

export const mpLogos = [
  {
    src: bitcoin,
    alt: bitcoin,
    url: "https://news.bitcoin.com/",
  },
  {
    src: bitcoininsider,
    alt: bitcoininsider,
    url: "https://www.bitcoininsider.org/",
  },
  {
    src: bitget,
    alt: bitget,
    url: "https://bonus.bitget.com/Y7LM99",
  },
  {
    src: bittwome,
    alt: bittwome,
    url: "https://bit2me.com/",
  },

  {
    src: blockchainmagazine,
    alt: blockchainmagazine,
    url: "https://blockchainmagazine.com/",
  },
  {
    src: blockchainreporter,
    alt: blockchainreporter,
    url: "https://blockchainreporter.net/",
  },
  {
    src: blockchaintoday,
    alt: blockchaintoday,
    url: "https://www.blockchaintoday.co.kr/",
  },
  {
    src: blockhead,
    alt: blockhead,
    url: "https://www.blockhead.co/tag/podcast/",
  },
  {
    src: catenaa,
    alt: catenaa,
    url: "https://investors.catenaa.com/",
  },
  {
    src: cim,
    alt: cim,
    url: "https://cryptoindiamagazine.com/",
  },
  {
    src: coinchapter,
    alt: coinchapter,
    url: "https://coinchapter.com/",
  },
  {
    src: coincu,
    alt: coincu,
    url: "https://coincu.com/",
  },
  {
    src: coinedition,
    alt: coinedition,
    url: "https://coinedition.com/",
  },
  {
    src: coingape,
    alt: coingape,
    url: "http://coingape.com/",
  },
  {
    src: coinpasar,
    alt: coinpasar,
    url: "https://coinpasar.sg/",
  },
  {
    src: coinpedia,
    alt: coinpedia,
    url: "https://coinpedia.org/",
  },
  {
    src: coinrank,
    alt: coinrank,
    url: "https://www.coinrank.io/",
  },
  {
    src: coinwire,
    alt: coinwire,
    url: "https://coinwirez.com/",
  },
  {
    src: cryptobreakingnews,
    alt: cryptobreakingnews,
    url: "https://www.cryptobreaking.com/",
  },
  {
    src: cryptodashnews,
    alt: cryptodashnews,
    url: "https://cryptonews.net/",
  },
  {
    src: cryptodotnews,
    alt: cryptodotnews,
    url: "https://crypto.news/",
  },
  {
    src: cryptonews,
    alt: cryptonews,
    url: "https://cryptonews.com//",
  },
  {
    src: cryptopolitan,
    alt: cryptopolitan,
    url: "https://www.cryptopolitan.com/",
  },
  {
    src: cryptoslate,
    alt: cryptoslate,
    url: "https://cryptoslate.com/",
  },
  {
    src: cryptoweekly,
    alt: cryptoweekly,
    url: "https://cryptoweekly.co/",
  },
  {
    src: disruptionbanking,
    alt: disruptionbanking,
    url: "https://www.disruptionbanking.com/",
  },
  {
    src: dlnews,
    alt: dlnews,
    url: "https://www.dlnews.com/",
  },
  {
    src: droomdroom,
    alt: droomdroom,
    url: "https://droomdroom.com/",
  },
  {
    src: forklog,
    alt: forklog,
    url: "https://forklog.com.ua/",
  },
  {
    src: fxstreet,
    alt: fxstreet,
    url: "https://www.fxstreet.com/",
  },
  {
    src: klarda,
    alt: klarda,
    url: "https://klarda.com/en",
  },
  {
    src: koreaittimes,
    alt: koreaittimes,
    url: "https://www.koreaittimes.com/",
  },
  {
    src: newschain,
    alt: newschain,
    url: "https://newzchain.com/",
  },
  {
    src: ngglobalmedia,
    alt: ngglobalmedia,
    url: "https://www.ncglobalmedia.com/",
  },
  {
    src: santiment,
    alt: santiment,
    url: "https://t.co/hxhgitN4Z4",
  },
  {
    src: startupnews,
    alt: startupnews,
    url: "https://startupnews.fyi/",
  },
  {
    src: theblockpedia,
    alt: theblockpedia,
    url: "https://theblockopedia.com/",
  },
  {
    src: thecoinrepublic,
    alt: thecoinrepublic,
    url: "https://www.thecoinrepublic.com/",
  },
  {
    src: thecryptonomist,
    alt: thecryptonomist,
    url: "https://en.cryptonomist.ch/",
  },
  {
    src: thejournalwire,
    alt: thejournalwire,
    url: "https://journal-wire.com/",
  },
];
