export const ROUTES = {
  ABOUT: "about-us",
  TECHNICAL: "technical",
  CONTACT_US: "contact-us",
  BUILD_WITH_US: "build-with-us",
  ECOSYSTEM: "ecosystem",
  DEQUIP: "dequip",
  CAREERS: "careers",
  RESOURCES: "resources",
  MEDIA_KIT: "https://drive.google.com/drive/folders/1YJtJEUIhaVR7U3EfXrWx0kAPhvSK_Fx0",
  GLOBAL_ROADSHOW: "https://beuncrackable.com/",
  QUANTUM_SECURITY_AWARENESS_DAY: "quantum-security-awareness-day",
  QUANTUM_MINDS_PODCAST: "quantum-minds-podcast",
  PRIVACY_POLICY: "privacy-policy",
  COOKIES_POLICY: "cookies-policy",
  TERMS_AND_CONDITIONS: "terms-and-conditions",
  NEXT_GEN_INNOVATORS: "next-gen-innovators",
  LAYERS_AND_LATTES: "layers-and-lattes",
  UNCRACKABLE_CONVERSATION: "the-uncrackable-conversation",
  QSAFE: "https://qsafewallet.com/",
  QRN_FAUCET: "https://faucet.quranium.org/",
  QRN_SCAN: "https://testnet.qrnscan.com/",
  NODE_SALE: "https://validators.quranium.org/",
};
